### ISSUE TITLE
Embracing simplicity

### ISSUE THREAD

**Issue by jschrier** [thomasegg3/automation_pedagogy_python#1]
Some directions towards further refinement

1. Convert all file import using Pandas (using read_csv) simplifies the approach (of having to do appends, type conversions) , and you already use pandas; I think it should also work OK with matplotlib.  
2. Doing the logistic regression with sci-kit learn (its simpler, less configuration, more generalizable)
3. Some minor typos scattered throughout

**Comment by jschrier** [comment]
(Also, in the post-lab notebook, I don't think you have a " Insert>File..." menu available; we'll want to think about the appropriate usage model for a beginner student.  (For now, I'm assuming they are just running Jupyter locally, so they need to find a file in their local filesystem)

**Comment by jschrier** [comment]
(in pre-lab notebook)

1. ```[LongDash]```
2. Absent hyperlink in learning goals paper link
3. The "libraries" introductory section is nice.  This is probably the right place to put a "test" that we can import the necessary libraries (matplotlib, scipy, numpy, scikit-learn)

**Comment by thomasegg3** [comment]
Just fixed most of these (some typos I will have to scout out when I return home) but I believe I addressed all of the other issues mentioned. I'll take another look in a few days.

**Comment by jschrier** [comment]
Enjoy your vacation! We can work on it when you get back...

On Wed, Jul 5, 2023 at 12:32 PM Tom Egg ***@***.***> wrote:

> Just fixed most of these (some typos I will have to scout out when I
> return home) but I believe I addressed all of the other issues mentioned.
> I'll take another look in a few days.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_thomasegg3_automation-5Fpedagogy-5Fpython_issues_1-23issuecomment-2D1622106799&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=TkdkMZKgCpYcE_rS3xubC7pX-Fv1fDBJWWAItU-ijMU&m=8soefwvlz24Lewx6Kemxmm1yaEgjwHbJix9XrzOMM0jqUf3QxmQevbJF1_fqnFNe&s=HEF3RrvPH_9YtKmaGeuxQIJ1uSu3oPEmlrRfHT18QOQ&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AB3WW55DIMDTGCSCS6IZJHLXOWJKDANCNFSM6AAAAAAZ7DNH4E&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=TkdkMZKgCpYcE_rS3xubC7pX-Fv1fDBJWWAItU-ijMU&m=8soefwvlz24Lewx6Kemxmm1yaEgjwHbJix9XrzOMM0jqUf3QxmQevbJF1_fqnFNe&s=TBqSxAFvSaFT8OyV8bl0VX_SahbaEfySb23oGKwmgFk&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
Joshua Schrier
Professor of Chemistry
Kim B. and Stephen E. Bepler Chair in Chemistry
Associate Department Chair for Undergraduate Studies
Fordham University
Department of Chemistry, JMH 616
441 E. Fordham Road
The Bronx, NY 10458
ph: +1 718-817-4453
Google Scholar link to papers
<https://scholar.google.com/citations?user=zJC_7roAAAAJ&hl=en>

**Comment by jschrier** [comment]
(pre-lab notebook CSV handling has not been migrated to pandas

in sections on `Exporting Instructions to the Real world` and `Importing Results and Fitting model`

**Comment by thomasegg3** [comment]
Migrated these to pandas!

**Comment by jschrier** [comment]
Just did another pass to clean up typos and make the text match the code, and sent this up the chain.
